In [8]:
import plotly.plotly as py

In [9]:
import plotly.graph_objs as go

In [10]:
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot

In [11]:
init_notebook_mode(connected=True)

In [14]:
import pandas as pd

In [23]:
df = pd.read_csv('2014_World_GDP.csv')

In [16]:
pwd

u'C:\\Users\\dilip'

In [24]:
df

                    COUNTRY  GDP (BILLIONS) CODE
0               Afghanistan           21.71  AFG
1                   Albania           13.40  ALB
2                   Algeria          227.80  DZA
3            American Samoa            0.75  ASM
4                   Andorra            4.80  AND
5                    Angola          131.40  AGO
6                  Anguilla            0.18  AIA
7       Antigua and Barbuda            1.24  ATG
8                 Argentina          536.20  ARG
9                   Armenia           10.88  ARM
10                    Aruba            2.52  ABW
11                Australia         1483.00  AUS
12                  Austria          436.10  AUT
13               Azerbaijan           77.91  AZE
14             Bahamas, The            8.65  BHM
15                  Bahrain           34.05  BHR
16               Bangladesh          186.60  BGD
17                 Barbados            4.28  BRB
18                  Belarus           75.25  BLR
19                  Belgium          527.80  BEL
20                   Belize            1.67  BLZ
21                    Benin            9.24  BEN
22                  Bermuda            5.20  BMU
23                   Bhutan            2.09  BTN
24                  Bolivia           34.08  BOL
25   Bosnia and Herzegovina           19.55  BIH
26                 Botswana           16.30  BWA
27                   Brazil         2244.00  BRA
28   British Virgin Islands            1.10  VGB
29                   Brunei           17.43  BRN
..                      ...             ...  ...
192                  Sweden          559.10  SWE
193             Switzerland          679.00  CHE
194                   Syria           64.70  SYR
195                  Taiwan          529.50  TWN
196              Tajikistan            9.16  TJK
197                Tanzania           36.62  TZA
198                Thailand          373.80  THA
199             Timor-Leste            4.51  TLS
200                    Togo            4.84  TGO
201                   Tonga            0.49  TON
202     Trinidad and Tobago           29.63  TTO
203                 Tunisia           49.12  TUN
204                  Turkey          813.30  TUR
205            Turkmenistan           43.50  TKM
206                  Tuvalu            0.04  TUV
207                  Uganda           26.09  UGA
208                 Ukraine          134.90  UKR
209    United Arab Emirates          416.40  ARE
210          United Kingdom         2848.00  GBR
211           United States        17420.00  USA
212                 Uruguay           55.60  URY
213              Uzbekistan           63.08  UZB
214                 Vanuatu            0.82  VUT
215               Venezuela          209.20  VEN
216                 Vietnam          187.80  VNM
217          Virgin Islands            5.08  VGB
218               West Bank            6.64  WBG
219                   Yemen           45.45  YEM
220                  Zambia           25.61  ZMB
221                Zimbabwe           13.74  ZWE

[222 rows x 3 columns]

In [35]:
df.loc[92]

COUNTRY           India
GDP (BILLIONS)     2048
CODE                IND
Name: 92, dtype: object